version: '3'
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
      - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
  server:
    image: amperecloud-server
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_HOST: db
      MONGO_PORT: 27017
      APP_MONGO_DB: ${APP_MONGO_DB}
      APP_MONGO_USER: ${APP_MONGO_USER}
      APP_MONGO_PASS: ${APP_MONGO_PASS}

  client:
    image: amperecloud-client
    depends_on:
      - server
    ports:
      - 4200:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
